# Generated by Django 3.1.7 on 2021-03-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'Patient'), (2, 'Doctor')], max_length=8),
        ),
    ]
