# Generated by Django 3.1.7 on 2021-04-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210402_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(default='O+', max_length=4),
            preserve_default=False,
        ),
    ]
