# Generated by Django 3.1.7 on 2021-03-11 11:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210311_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonw_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+966566788329', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
