# Generated by Django 3.1.7 on 2021-03-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phonw_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phonw_number',
            new_name='phone_number',
        ),
    ]
