# Generated by Django 3.1.7 on 2021-04-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Rejected', max_length=10),
        ),
    ]
