# Generated by Django 3.1.7 on 2021-04-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20210404_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_email',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_email',
            new_name='patient_id',
        ),
    ]
